- name: Install Clickhouse
  hosts: clickhouse
  roles:
    - role: clickhouse
      tags: clickhouse

- name: Install and configure Vector
  hosts: vector
  roles:
    - role: vector-role
      tags: vector
    
  
- name: Install Lighthouse
  hosts: lighthouse
  roles:
    - role: lighthouse-role
      tags: lighthouse