---
clickhouse:
  hosts:
    clickhouse-01:
      ansible_host: 158.160.106.78

vector:
  hosts:
    vector-01:
      ansible_host: 158.160.104.37

lighthouse:
  hosts:
    lighthouse-01:
      ansible_host: 158.160.126.115
